name: scaled_box
description: A widget that proportionally scales its child, affecting its layout.
version: 0.0.1
homepage: https://github.com/madewithfelt/scaled_box

environment:
  flutter: '>=1.14.0'
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
